# scripts/setup/generate.sh
# Secret generation and template rendering.

generate_config() {
    info "Generating secrets…"

    POSTGRES_PASSWORD="$(generate_secret)"
    REGISTRATION_SHARED_SECRET="$(generate_secret)"
    MACAROON_SECRET_KEY="$(generate_secret)"
    FORM_SECRET="$(generate_secret)"
    COTURN_SECRET="$(generate_secret)"
    LIVEKIT_KEY="matrix"
    LIVEKIT_SECRET="$(generate_secret)"

    if [[ "$ENABLE_SSO" != "true" || -z "${OIDC_PROVIDERS_JSON:-}" ]]; then
        OIDC_PROVIDERS_JSON="[]"
        OIDC_PROVIDER_COUNT="0"
    fi

    info "Detecting public IP address…"
    SERVER_IP="$(curl -fsSL --max-time 10 https://api4.ipify.org 2>/dev/null || true)"
    if [[ -z "$SERVER_IP" ]]; then
        SERVER_IP="$(curl -fsSL --max-time 10 https://ifconfig.me 2>/dev/null || true)"
    fi
    if [[ -z "$SERVER_IP" ]]; then
        warn "Could not auto-detect public IP. Edit modules/calls/coturn/turnserver.conf and set 'external-ip' manually."
        SERVER_IP="REPLACE_WITH_YOUR_PUBLIC_IP"
    else
        success "Public IP detected: ${SERVER_IP}"
    fi

    success "Secrets generated."

    SHARED_REDIS_HOST="${SHARED_REDIS_HOST:-matrix_redis}"
    SHARED_REDIS_PORT="${SHARED_REDIS_PORT:-6379}"
    SHARED_REDIS_URL="${SHARED_REDIS_URL:-redis://${SHARED_REDIS_HOST}:${SHARED_REDIS_PORT}}"

    if [[ "$SERVER_NAME" == "$MATRIX_DOMAIN" ]]; then
        CADDY_MATRIX_HOSTS="$MATRIX_DOMAIN"
    else
        CADDY_MATRIX_HOSTS="$MATRIX_DOMAIN, $SERVER_NAME"
    fi

    info "Writing ${DEPLOY_ENV}…"
    cat > "$DEPLOY_ENV" <<EOF
# matrix-easy-deploy environment
# Generated by setup.sh on $(date -u +"%Y-%m-%d %H:%M UTC")
# Keep this file private — it contains secrets.

MATRIX_DOMAIN=${MATRIX_DOMAIN}
SERVER_NAME=${SERVER_NAME}
ADMIN_USERNAME=${ADMIN_USERNAME}

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
REGISTRATION_SHARED_SECRET=${REGISTRATION_SHARED_SECRET}
MACAROON_SECRET_KEY=${MACAROON_SECRET_KEY}
FORM_SECRET=${FORM_SECRET}

ENABLE_REGISTRATION=${ENABLE_REGISTRATION}
ENABLE_SSO=${ENABLE_SSO}
OIDC_PROVIDER_COUNT=${OIDC_PROVIDER_COUNT}
OIDC_PROVIDER_NAMES=${OIDC_PROVIDER_NAMES}
OIDC_PROVIDERS_JSON=${OIDC_PROVIDERS_JSON}
INSTALL_ELEMENT=${INSTALL_ELEMENT}
ELEMENT_DOMAIN=${ELEMENT_DOMAIN}

SERVER_IP=${SERVER_IP}
COTURN_SECRET=${COTURN_SECRET}
LIVEKIT_DOMAIN=${LIVEKIT_DOMAIN}
LIVEKIT_KEY=${LIVEKIT_KEY}
LIVEKIT_SECRET=${LIVEKIT_SECRET}

SHARED_REDIS_HOST=${SHARED_REDIS_HOST}
SHARED_REDIS_PORT=${SHARED_REDIS_PORT}
SHARED_REDIS_URL=${SHARED_REDIS_URL}
CADDY_MATRIX_HOSTS=${CADDY_MATRIX_HOSTS}
EOF
    chmod 600 "$DEPLOY_ENV"
    success ".env written."

    vars_file="$(mktemp)"
    trap 'rm -f "$vars_file"' EXIT

    cat > "$vars_file" <<EOF
MATRIX_DOMAIN=${MATRIX_DOMAIN}
SERVER_NAME=${SERVER_NAME}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
REGISTRATION_SHARED_SECRET=${REGISTRATION_SHARED_SECRET}
MACAROON_SECRET_KEY=${MACAROON_SECRET_KEY}
FORM_SECRET=${FORM_SECRET}
ENABLE_REGISTRATION=${ENABLE_REGISTRATION}
FEDERATION_WHITELIST=${FEDERATION_WHITELIST}
ALLOW_PUBLIC_ROOMS_FEDERATION=${ALLOW_PUBLIC_ROOMS_FEDERATION}
OIDC_PROVIDERS_JSON=${OIDC_PROVIDERS_JSON}
ELEMENT_DOMAIN=${ELEMENT_DOMAIN}
SERVER_IP=${SERVER_IP}
COTURN_SECRET=${COTURN_SECRET}
LIVEKIT_DOMAIN=${LIVEKIT_DOMAIN}
LIVEKIT_KEY=${LIVEKIT_KEY}
LIVEKIT_SECRET=${LIVEKIT_SECRET}
SHARED_REDIS_HOST=${SHARED_REDIS_HOST}
SHARED_REDIS_PORT=${SHARED_REDIS_PORT}
SHARED_REDIS_URL=${SHARED_REDIS_URL}
CADDY_MATRIX_HOSTS=${CADDY_MATRIX_HOSTS}
EOF

    info "Rendering Caddyfile…"
    local _caddyfile_template
    if [[ "$INSTALL_ELEMENT" == "true" ]]; then
        _caddyfile_template="${SCRIPT_DIR}/caddy/Caddyfile.template"
    else
        _caddyfile_template="${SCRIPT_DIR}/caddy/Caddyfile-no-element.template"
    fi
    render_template \
        "$_caddyfile_template" \
        "${SCRIPT_DIR}/caddy/Caddyfile" \
        "$vars_file"
    if grep -q '{{[A-Z_][A-Z0-9_]*}}' "${SCRIPT_DIR}/caddy/Caddyfile"; then
        die "Caddyfile still contains unresolved template placeholders. Aborting to avoid booting broken Caddy config."
    fi
    success "caddy/Caddyfile written."

    info "Rendering homeserver.yaml…"
    render_template \
        "${SCRIPT_DIR}/modules/core/synapse/homeserver.yaml.template" \
        "${SCRIPT_DIR}/modules/core/synapse/homeserver.yaml" \
        "$vars_file"
    success "modules/core/synapse/homeserver.yaml written."

    if [[ "$INSTALL_ELEMENT" == "true" ]]; then
        info "Rendering element/config.json…"
        render_template \
            "${SCRIPT_DIR}/modules/core/element/config.json.template" \
            "${SCRIPT_DIR}/modules/core/element/config.json" \
            "$vars_file"
        success "modules/core/element/config.json written."
    fi

    info "Rendering coturn/turnserver.conf…"
    render_template \
        "${SCRIPT_DIR}/modules/calls/coturn/turnserver.conf.template" \
        "${SCRIPT_DIR}/modules/calls/coturn/turnserver.conf" \
        "$vars_file"
    success "modules/calls/coturn/turnserver.conf written."

    info "Rendering livekit/livekit.yaml…"
    render_template \
        "${SCRIPT_DIR}/modules/calls/livekit/livekit.yaml.template" \
        "${SCRIPT_DIR}/modules/calls/livekit/livekit.yaml" \
        "$vars_file"
    success "modules/calls/livekit/livekit.yaml written."
}
